pool:
  name: test
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1

  displayName: 'Publish artifacts: drop'



